### ISSUE TITLE
Garbage text in various chapters on manning.com (livebook?) rendering

### ISSUE THREAD

**Issue by setr** [rust-in-action/code#25]
Was randomly skimming on [manning](https://www.manning.com/books/rust-in-action) and I'm encountering a lot of garbage text. I'm not sure if its specific to this book or a general issue with manning. However, I randomly tried book [Full Stack Python](https://www.manning.com/books/full-stack-python-security) and that renders without issue.

All chapters seem to be affected. At least, Chapters 4.1, 5, 6, 7.4.1 I've directly looked at.

AFAICT:

1. Intro paragraph per chapter seems to consistently render correctly. 
2. First paragraph of first section per chapter sometimes renders correctly, sometimes doesn't.
3. Code blocks render correctly. The line preceding a codeblock renders incorrectly, sometimes
4. Paragraphs otherwise render as garbage
5. Links, Headers & Inline Code always render correctly

Windows 10
**Chrome** Version 91.0.4472.124 (Official Build) (64-bit)

No extensions, ad blockers, etc. 
Tried refreshing, killing cookies, browser, etc.

There are a couple JS errors occurring, but since they exist for both books, I don't think that's the issue.

# Rust In Action - garbage text
![image](https://user-images.githubusercontent.com/7907343/124167434-dcb8ae00-da58-11eb-93ef-bd3832aa3175.png)

# Full Stack Python - renders correctly
![image](https://user-images.githubusercontent.com/7907343/124168516-1c33ca00-da5a-11eb-8d51-34e344719e00.png)

**Comment by Sam-Vimes** [comment]
Hi @setr 

The garbage text is actually encrypted. Manning has a feature whereby one can "unlock" (i.e. decrypt) sections of a so-called livebook one wants to read, by applying tokens that one can buy. This allows you to essentially buy just the parts of a book that may be of interest to you. 

Go to https://livebook.manning.com/ and click "More information on livebook" in the top right-hand corner for details. Tokens can be purchased from https://www.manning.com/tokens.

Hope this helps.

**Comment by timClicks** [comment]
Hi Neil, thanks for your interest in Rust in Action. After the 1st chapter
or so, you need to buy the books that you want to read via the liveBook
platform.
