### ISSUE TITLE
Update the code!!

### ISSUE THREAD

**Issue by timClicks** [rust-in-action/code#26]
The book has been released! I need to update the code to match.

**Comment by ropewalker** [comment]
@timClicks Would you be willing to accept pull requests for this, or would you rather prefer to do it all by yourself? I wonder if there's a way to help with this.

**Comment by timClicks** [comment]
Thank you for the offer Dima, but I don't accept any pull requests into
this repository for copyright reasons. I will get the code up tonight.

**Comment by runiq** [comment]
This interested reader would like to know how far along you are :)

**Comment by timClicks** [comment]
I have pushed the final code to the `1st-edition` branch. Sorry that it took me so long.
