### ISSUE TITLE
code not compilling

### ISSUE THREAD

**Issue by JamRemco** [rust-in-action/code#27]
The code @ [Animals specialization](https://github.com/rust-in-action/code/blob/meap-v12/ch1/ch1-animals-specialization.rs) is not compiling
or is it a codeexample the shows what does not work
Sorry newb here, google brought me here when i was searching for specialization/generics.

Regards Remco

**Comment by timClicks** [comment]
Hi @JamRemco. That file should not have appeared in the repository. It is broken. Sorry.

Do you still need help with generics?
