### ISSUE TITLE
ch2-mandelbrot doesn't compile

### ISSUE THREAD

**Issue by ropewalker** [rust-in-action/code#28]
`all_rows` doesn't exist in this scope: https://github.com/rust-in-action/code/blob/7d7955e9605ca156f6eb7cb5bc9f124c97927d25/ch2/ch2-mandelbrot/src/main.rs#L28

**Comment by ropewalker** [comment]
FWIW the code in the book doesn't have this issue.

**Comment by Spikhalskiy** [comment]
`all_rows` should be replaced with `rows`

**Comment by florentsorel** [comment]
You can replace `all_rows.push(row); ` by `rows.push(row); `

It compile but the output contains only empty lines... #29 

I use the last version of the PDF.

**Comment by timClicks** [comment]
Thanks for raising this issue @ropewalker and to @s1ck for posting a fix.

**Comment by alper** [comment]
The book ePub version that I got also contains this issue.
