### ISSUE TITLE
ch2-mandelbrot renders whitespaces

### ISSUE THREAD

**Issue by ropewalker** [rust-in-action/code#29]
https://github.com/rust-in-action/code/blob/7d7955e9605ca156f6eb7cb5bc9f124c97927d25/ch2/ch2-mandelbrot/src/main.rs#L73-L74

This should be `calculate_mandelbrot(1000, -2.0, 1.0, -1.0, 1.0, 80, 24)` as mentioned in https://www.reddit.com/r/rust/comments/o980ip/rust_in_action_is_released/h3aktuf

**Comment by ropewalker** [comment]
FWIW the code in the book is correct.

**Comment by jakob-fischer** [comment]
My PDF (which I was told is the release version) has the same problem. So I'd assume this is a mistake that was introduced in the final edit.

**Comment by JoelMon** [comment]
I've made the changes mentioned and still getting white spaces...

**Comment by timClicks** [comment]
> So I'd assume this is a mistake that was introduced in the final edit.

You're correct. I made a stupid rushed edit and accidentally copy + pasted the wrong version. I will get a fix pushed to the repository now.
