### ISSUE TITLE
Multiple patterns overlap on their endpoints in ch2-mandelbrot

### ISSUE THREAD

**Issue by ropewalker** [rust-in-action/code#30]
Multiple patterns overlap on their endpoints here:
https://github.com/rust-in-action/code/blob/7d7955e9605ca156f6eb7cb5bc9f124c97927d25/ch2/ch2-mandelbrot/src/main.rs#L55-L62
There probably should be mutually exclusive ranges instead.

**Comment by timClicks** [comment]
Thanks for the suggestion @ropewalker. I've updated the code ✨ .
