### ISSUE TITLE
ch 1 - penguins - unknown character escape

### ISSUE THREAD

**Issue by KevinBatdorf** [rust-in-action/code#32]
I'm not really sure how to fix it,  but it won't compile. Listing 1.2 on page 9.

I tried updating rust, etc but nothing changed

![Screen Shot 2021-07-31 at 11 01 16 PM](https://user-images.githubusercontent.com/1478421/127757694-5a445948-3019-4fac-b415-b5050a6f2fa4.png)

![Screen Shot 2021-07-31 at 10 58 48 PM](https://user-images.githubusercontent.com/1478421/127757662-7c5a2156-c9b5-4eaa-b3a2-91bb740457f9.png)

Obviously I'm at the start of the book so can't offer much help, but if I figure out the solution I'll leave a reply here.

**Comment by KevinBatdorf** [comment]
Okay so just removing the two comments at the start fixed it. You can see the error here as well: [play.rust-lang.org](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&code=fn%20main()%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%3C1%3E%0A%20%20let%20penguin_data%20%3D%20%22%5C%20%20%20%20%20%2F%2F%20%3C2%3E%0A%20%20common%20name%2Clength%20(cm)%0A%20%20Little%20penguin%2C33%0A%20%20Yellow-eyed%20penguin%2C65%0A%20%20Fiordland%20penguin%2C60%0A%20%20Invalid%2Cdata%0A%20%20%22%3B%0A%0A%20%20let%20records%20%3D%20penguin_data.lines()%3B%0A%0A%20%20for%20(i%2C%20record)%20in%20records.enumerate()%20%7B%0A%20%20%20%20if%20i%20%3D%3D%200%20%7C%7C%20record.trim().len()%20%3D%3D%200%20%7B%20%20%2F%2F%20%3C3%3E%0A%20%20%20%20%20%20continue%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20let%20fields%3A%20Vec%3C_%3E%20%3D%20record%20%20%20%20%20%2F%2F%20%3C4%3E%0A%20%20%20%20%20%20.split(%27%2C%27)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%3C5%3E%0A%20%20%20%20%20%20.map(%7Cfield%7C%20field.trim())%20%20%20%20%2F%2F%20%3C6%3E%0A%20%20%20%20%20%20.collect()%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%3C7%3E%0A%0A%20%20%20%20if%20cfg!(debug_assertions)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%3C8%3E%0A%20%20%20%20%20%20eprintln!(%22debug%3A%20%7B%3A%3F%7D%20-%3E%20%7B%3A%3F%7D%22%2C%0A%09%20%20%20%20%20%20%20%20%20%20%20%20%20record%2C%20fields)%3B%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%3C9%3E%0A%20%20%20%20%7D%0A%0A%20%20%20%20let%20name%20%3D%20fields%5B0%5D%3B%0A%20%20%20%20if%20let%20Ok(length)%20%3D%20fields%5B1%5D.parse%3A%3A%3Cf32%3E()%20%7B%20%2F%2F%20%3C10%3E%0A%20%20%20%20%20%20%20%20println!(%22%7B%7D%2C%20%7B%7Dcm%22%2C%20name%2C%20length)%3B%20%20%20%20%20%20%20%20%2F%2F%20%3C11%3E%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Comment by krg-digital** [comment]
Looks like the "comment" is actually in the string, here. The compiler seems to be complaining about the space that follows the escape (the "\") as it wants to interpret what follows the escape as an escape character, however the space character isn't a valid escape character. A bit of an oversight with these "annotation" comments, I'd guess.

**Comment by timClicks** [comment]
> A bit of an oversight with these "annotation" comments, I'd guess.

Yes.. I'll go and pull them out. Thanks for raising this @KevinBatdorf. I'm sorry that you encountered this frustrating problem.

**Comment by KevinBatdorf** [comment]
All good! Sometimes you learn more with minor obstacles like this so long as you power through them! Looking forward to the rest of the book, thanks.
