### ISSUE TITLE
ch-5: missing mantissa in decode snippet ch5/ch5-visualizing-f32.rs

### ISSUE THREAD

**Issue by dogeplusplus** [rust-in-action/code#37]
Note that the snippet for `ch5/ch5-visualizing-f32.rs` is missing the `mantissa` variable. This can be easily fixed by adding this before the for loop in `decode`. He does mention this in the book but the listing seems to be missing it.
```
let mut mantissa: f32 = 1.0;
```

https://github.com/rust-in-action/code/blob/7d7955e9605ca156f6eb7cb5bc9f124c97927d25/ch5/ch5-visualizing-f32.rs#L28-L49

**Comment by timClicks** [comment]
Thank you for raising this @dogeplusplus. I'm surprised that this bug got through.

**Comment by timClicks** [comment]
I've fixed the code. Thank you again!
