### ISSUE TITLE
Chapter 2 - 2.10.1 Arrays - Listing 2.21

### ISSUE THREAD

**Issue by JoelMon** [rust-in-action/code#38]
Hello buddy!

Great book! Found a trivial discrepancy in Listing 2.21

The result in the LiveBook is shown as:
> [1, 2, 3]:     1 + 10 = 11    2 + 10 = 12    3 + 10 = 13    (Σ[1, 2, 3] = 6)
[1, 2, 3]:     1 + 10 = 11    2 + 10 = 12    3 + 10 = 13    (Σ[1, 2, 3] = 6)
[0, 0, 0]:     0 + 10 = 10    0 + 10 = 10    0 + 10 = 10    (Σ[0, 0, 0] = 0)
[0, 0, 0]:     0 + 10 = 10    0 + 10 = 10    0 + 10 = 10    (Σ[0, 0, 0] = 0)

The sum bit has the sum symbol `Σ` but the code doesn't have it.

The code as is is missing the `Σ` symbol:
```rust
fn main() {
  let one             = [1, 2, 3];
  let two: [u8; 3]    = [1, 2, 3];
  let blank1          = [0; 3];
  let blank2: [u8; 3] = [0; 3];
 
  let arrays = [one, two, blank1, blank2];
 
  for a in &arrays {
    print!("{:?}: ", a);
    for n in a.iter() {
      print!("\t{} + 10 = {}", n, n+10);
    }
 
    let mut sum = 0;
    for i in 0..a.len() {
      sum += a[i];
    }
    println!("\t({:?} = {})", a, sum);
  }
}
```

Line 19 should be:
```rust
      print!("\tΣ{} + 10 = {}", n, n+10);
```

**Comment by timClicks** [comment]
oof

Will get this fixed

**Comment by timClicks** [comment]
Interestingly, the code in the repository is correct. Sorry about this slip up. You've got a sharp eye! 

https://github.com/rust-in-action/code/blob/509fe8c9d0f26b994a6bd7aa295bc16be00c05eb/ch2/ch2-3arrays.rs#L19
