### ISSUE TITLE
ch7 actionkv2

### ISSUE THREAD

**Issue by ianoc** [rust-in-action/code#4]
This section discusses storing the index in with the data to avoid having to rebuild it on load, though it seems looking at the code the entire index is still built on every load. So it would provide no benefit I believe. (though is an interesting description of in-lining the index in with the data)

**Comment by timClicks** [comment]
I'm closing this issue as I don't want to re-architect the code.

**Comment by GtTmy** [comment]
I also thought about it and found this issue.

I did benchmark using hyperfine and realized akv_disk is not faster than akv_mem.
(dummy1000000.dat contains 1000000 data and its index data.)

```
$ hyperfine --warmup 1 'target/release/akv_disk dummy1000000.dat get 1' 'target/release/akv_mem dummy1000000.dat get 1'
Benchmark 1: target/release/akv_disk dummy1000000.dat get 1
  Time (mean ± σ):      1.348 s ±  0.005 s    [User: 0.764 s, System: 0.580 s]
  Range (min … max):    1.342 s …  1.361 s    10 runs
 
Benchmark 2: target/release/akv_mem dummy1000000.dat get 1
  Time (mean ± σ):      1.103 s ±  0.003 s    [User: 0.541 s, System: 0.561 s]
  Range (min … max):    1.098 s …  1.110 s    10 runs
 
Summary
  'target/release/akv_mem dummy1000000.dat get 1' ran
    1.22 ± 0.01 times faster than 'target/release/akv_disk dummy1000000.dat get 1'
```
