### ISSUE TITLE
Your definition of NTP offset is wrong 

### ISSUE THREAD

**Issue by 8thMage** [rust-in-action/code#51]
Hi, thanks for the book and the much helping source code. 
I think I found a problem here:
https://github.com/rust-in-action/code/blob/cff02d525ac50a1aa16dafba9780da66fc6d6661/ch9/ch9-clock3/src/main.rs#L41-L44
Per the definition in https://en.wikipedia.org/wiki/Network_Time_Protocol your code should be 
`  let offset = (self.t2 - self.t1) + (self.t3 - self.t4); `

Both this code and the book wording threw me off balance enough to check the wikipedia article, as your code doesn't have any difference between delta and theta, except for the 2 factor. their fixed definitions makes much more sense.

**Comment by timClicks** [comment]
Wow, that's a significant mistake. Thank you very much for pointing it out.

Now that Rust has Unicode identifiers, I wonder if I should update the code to make use of them. Probably not with this edition.

**Comment by timClicks** [comment]
Interestingly, it's correct later in the definition of `delay()`

https://github.com/rust-in-action/code/blob/cff02d525ac50a1aa16dafba9780da66fc6d6661/ch9/ch9-clock3/src/main.rs#L46-L49

**Comment by 8thMage** [comment]
I'm sorry but this has the same value, just the different t's are in different permutation. The offset should not have been delay / 2, but the t's in different signs. Should I open a pr?
