### ISSUE TITLE
Error in text in chapter 2.2.1

### ISSUE THREAD

**Issue by Freudie** [rust-in-action/code#58]
The text reads: 
Listing 2.2 prints a + b = 30 to the console

However, the code says: println!("( a + b ) + ( c + d ) = {}", e);

So it should say:
Listing 2.2 prints ( a + b ) + ( c + d ) = 90 to the console

**Comment by timClicks** [comment]
Thanks for reporting this. I have included it in a list of corrections for the publisher.
