### ISSUE TITLE
Code uses pre rust-2018 conventions

### ISSUE THREAD

**Issue by SillyMoo** [rust-in-action/code#6]
The code seems to use pre rust-2018 conventions. For example in the first chapter the code:

```#[macro_use]  // <3> Syntax to indicate that we want to import macros from another module
extern crate serde_derive;   // <3>
...
#[derive(Serialize)] // <6> Automatically generate a string representation of this struct (which will be used as JSON)
struct Timestamp { // <7> Syntax to create a custom type 
```

Can be re-written as 
```
use serde::Serialize;
...
#[derive(Serialize)] // <6> Automatically generate a string representation of this struct (which will be used as JSON)
struct Timestamp { // <7> Syntax to create a custom type 
```

**Comment by timClicks** [comment]
Thanks for reporting this issue. You're correct. (The example was in fact written in 2017!) I've actually updated this example, but neglected to update this repository.

I'll keep this issue open until I've updated things here.

Thanks again for reporting the issue!

**Comment by timClicks** [comment]
FWIW this situation is increasingly improving. There shouldn't be any 2015 edition examples within the first 5 chapters as of MEAP 13.

**Comment by dmgolembiowski** [comment]
Hi <3
I've spotted another one from Section 2.5.5 underneath _Break from Nested Loops_

```rs
    'outer: for x in 0.. {
        for y in 0.. {
            for z in 0.. {
                if x + y + z > 1000 {
                    break 'outer;
                }
            }
        }
    }
```

**Comment by timClicks** [comment]
This has been resolved. Thanks again for the report.
