### ISSUE TITLE
Ch8: send http requests using newer version of reqwest

### ISSUE THREAD

**Issue by SteveLauC** [rust-in-action/code#69]
The source code of this example uses `reqwest@0.9` to send HTTP requests, perhaps this is for the reason that the newer version of `reqwest` switches to async mode on the top of `tokio`. 
If you wanna use the newer version of `reqwest` and still send sync requests, use the code snippet below:
```rust
// main.rs
use std::error::Error;

use reqwest;

fn main() -> Result<(), Box<dyn Error>> { 
    let url = "http://www.rustinaction.com/";
    let mut response = reqwest::blocking::get(url)?; // use reqwest::blocking::get() to send sync request 

    let content = response.text()?;
    print!("{}", content);

    Ok(())
}
```
```rust
// Cargo.toml
...
[dependencies]
reqwest = { version="0.11.8", features = ["blocking"] } // ! enable the blocking feature
```
BTW, here is the link to [reqwest::blocking](https://docs.rs/reqwest/0.11.8/reqwest/blocking/index.html).
:)

**Comment by timClicks** [comment]
This is a reasonable suggestion @SteveLauC, but it is more appropriate for a second edition of the book.
